### ISSUE TITLE
GetDailyReturn ought not to be match on the day

### ISSUE THREAD

**Issue by victorbrun** [maxijohansson/ccm-db-api#15]
Currently the GetDailyReturn routine returns a 1 if there is no price data for the needed day, which does not catch the whole picture. If I would to request the 5-day return for a given instrument and five days ago the market was closed, the function will return 1, even though there has been a return since that day. Thus the routine should return the return counting from the nearest day to today upon which there exists price data.

**Comment by HEriks** [comment]
Works as expected, closing the issue
